#ifndef EXCEPTION
#define EXCEPTION

enum PNG_ERRORS{
    PNG_OPEN_CREATE_FILE_ERROR,
    PNG_NOT_PNG,
    PNG_READ_STRUCT_ERROR,
    PNG_INFO_STRUCT_ERROR,
    PNG_INITIALIZATION_ERROR,
    PNG_READ_IMAGE_ERROR,
    PNG_MEMORY_ERROR,
    PNG_EMPTY_ERROR,
    PNG_WRITE_STRUCT_ERROR,
    PNG_WRITE_INFO_ERROR,
    PNG_WRITE_IMAGE_ERROR,
    PNG_WRITE_END_ERROR,
    PNG_COLOR_ERROR,
    PNG_COORDINATES_ERROR,
    PNG_INVALID_COUNTS,
};


class PNGException{
private:
    PNG_ERRORS error;
public:
    PNGException(PNG_ERRORS error){
        this->error=error;
    }
    
    PNG_ERRORS getError(){return error;}
};

#endif
